### ISSUE TITLE
Some m3u8 file does not load video

### ISSUE THREAD

**Issue by pareshios** [garynewby/HLS-video-offline-caching#1]
Some m3u8 file does not load video

**Comment by pareshios** [comment]
It does loads the audio but no video is being displayed while playing

**Comment by shlomiatar** [comment]
I think it’s because it’s based on another project, and that project only caches .ts files. 

Some new HLS playlists use mp4/m4a extensions for fragmented MP4s

**Comment by garynewby** [comment]
Should now work with fragmented mp4, added a test stream.
